server:
  port: 8006
  
spring:
  application:
    name:  API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
#      routes:
#        - id: event-service
#          uri: http://localhost:8016
#          predicates:
#            - Path=/api/events/**
#        - id: event-service
#          uri: http://localhost:8016
#          predicates:
#            - Path=/api/participated-users/**
#
#        - id: notification-service
#          uri: http://localhost:8014
#          predicates:
#            - Path=/api/notification/**
#        - id: notification-service
#          uri: http://localhost:8014
#          predicates:
#            - Path=/sms/**
#
#        - id: admin-service
#          uri: http://localhost:8010
#          predicates:
#          - Path=/api/gym/**
#        - id: admin-service
#          uri: http://localhost:8010
#          predicates:
#          - Path=/api/gym/equipments/**
#        - id: admin-service
#          uri: http://localhost:8010
#          predicates:
#          - Path=/api/gym/subscriptions/**
#        - id: admin-service
#          uri: http://localhost:8010
#          predicates:
#          - Path=/api/gym/trainers/**
#
#        - id: feedback-service
#          uri: http://localhost:8018
#          predicates:
#          - Path=/api/feedback/**
#
#        - id: payment-service
#          uri: http://localhost:8015
#          predicates:
#          - Path=/payments/**
#
#        - id: chatting-service
#          uri: http://localhost:8011
#          predicates:
#          - Path=/chats/**
#        - id: chatting-service
#          uri: http://localhost:8011
#          predicates:
#          - Path=/user/**
#
#        - id: Registration
#          uri: http://localhost:8017
#          predicates:
#          - Path=/auth/**
#
#        - id: login-service
#          uri: http://localhost:8014
#          predicates:
#          - Path=/api/v1/auth/**
#
#        - id: product-webapp-service
#          uri: http://localhost:8019
#          predicates:
#            - Path=/**
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    register-with-eureka: true
    fetch-registry: true
        
          
          
          
            
            